### ISSUE TITLE
works on macOS?

### ISSUE THREAD

**Issue by nullhook** [eiln/avd#1]
does this driver work on macOS?

**Comment by eiln** [comment]
This repo is for generating the instruction stream. Kernel/firmware-side is https://github.com/AsahiLinux/m1n1/pull/376. Frankly the kernel part is not extremely demanding, and you could unload their AppleAVD kext and port m1n1.fw.avd to XNU (yourself), but, why? Apple's AVD driver works in macOS. This isn't CoreML/ANE (VideoToolbox is nothing compared to that), what is the goal/issue?
